version: '2.0'
services:
  app:
    # image: divante/vue-storefront:latest
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    env_file: docker/vue-storefront/default.env
    restart: on-failure
    mem_limit: 1G

  nginx:
    restart: on-failure
    image: nginx
    volumes:
    - ./docker/vue-storefront/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80

