name: Run tests

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get cached dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Run linter
        run: yarn lint

  validate_core:
    name: Validate core

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get cached dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build core
        run: yarn build:core

      - name: Test core
        run: yarn test:core --coverage
      
      #- name: Display core coverage
      #  run: cat ./packages/core/coverage/lcov.info | coveralls

      - name: Test CLI
        run: yarn test:cli --coverage
      
      #- name: Display CLI coverage
      #  run: cat ./packages/core/cli/coverage/lcov.info | coveralls

  validate_integrations:
    name: Validate ${{ matrix.integration }} ${{ matrix.part }}

    needs: validate_core

    runs-on: ubuntu-latest

    strategy:
      matrix:
        integration:
          - about-you
          - boilerplate
          - commercetools
          - shopify
        
        part:
          - composables
          - api-client
          - theme

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get cached dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      
      - name: Build core
        run: yarn build:core

      - name: Build ${{ matrix.part }}
        run: cd packages/${{ matrix.integration }}/${{ matrix.part }} && yarn build
      
      - name: Test ${{ matrix.part }}
        run: cd packages/${{ matrix.integration }}/${{ matrix.part }} && yarn test --passWithNoTests --coverage
      
      #- name: Display ${{ matrix.integration }} ${{ matrix.part }} coverage
      #  run: cat ./packages/${{ matrix.integration }}/${{ matrix.part }}/coverage/lcov.info | coveralls
